### ISSUE TITLE
Does this work with micropython?

### ISSUE THREAD

**Issue by achapkowski** [google-coral/pycoral#105]
### Description

On the microcontroller offering, does it work with micropython?
I couldn’t find any documentation on this.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

Dev Board

### Other Devices

Rapsberry Pi 4

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
> On the microcontroller offering, does it work with micropython?

Hi, which microcontroller are you referring to here?

**Comment by achapkowski** [comment]
I'm referring to this board: https://coral.ai/products/dev-board-micro/

**Comment by hjonnala** [comment]
No, it doesn't work with micropython. It works with CoralMicro API: https://coral.ai/docs/dev-board-micro/get-started/#the-software

**Comment by achapkowski** [comment]
@hjonnala thank you, are there are any thoughts of adding support for micropython?  I didn't know if there was a roadmap anywhere.

**Comment by hjonnala** [comment]
No, we don't have any plans of adding support for micropython.

**Comment by achapkowski** [comment]
Ok thank you.  Hopefully you can add it to the roadmap in the future.
