### ISSUE TITLE
ModuleNotFoundError: No module named 'pycoral'

### ISSUE THREAD

**Issue by bme323** [google-coral/pycoral#107]
### Description

Hi all,

I am trying to follow the Coral 'Get started with the USB Accelerator' demo and run the parrot demo (step 3 of part 3), however when executing, I get the error message shown.

![2023-03-06-221602_1920x1080_scrot](https://user-images.githubusercontent.com/84109305/223254523-942c4542-77da-4c22-afe8-245ae8d69f61.png)

Info:
- Raspberry Pi 4B
- 32-bit arm7l  
- downgraded python 3.7.12 from python 3.9.x

I have tried running the 32-bit whl. file and also changing directory name and continue getting error messages.

Any help appreciated.

Thanks

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install, Support

### Operating System

Linux

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.7, Python 3.9

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "examples/classify_image.py", line 37, in <module>
    from pycoral.adapters import classify 
ModuleNotFoundError: No module named 'pycoral'
```
</details>

**Comment by hjonnala** [comment]
Hi, can you please share the output of below command as root user and without root user..

```
hemanthj@:~$ python3 -c "import tflite_runtime as tflite; print('tflite runtime vesrion:', tflite.__version__);import pycoral; print('pycoral version:', pycoral.__version__)"
tflite runtime vesrion: 2.5.0.post1
pycoral version: 2.0.0
```

**Comment by bme323** [comment]
Hi Hemanth,

Here is my output as root user and non-root user. I have not installed tflite. Is this a prerequisite for the https://coral.ai/docs/accelerator/get-started/#pycoral-on-linux demo? 

![image](https://user-images.githubusercontent.com/84109305/223875501-34a8fd21-ac07-4bec-8dc7-4492a3064528.png)
![image](https://user-images.githubusercontent.com/84109305/223875883-6126cf14-2fb0-43e5-ae24-d8394937b115.png)

**Comment by hjonnala** [comment]
Could you please uninstall the exsiting packages and try the installation again. Please share the installation logs and output of below command. Thanks!!

`python3 -c "import tflite_runtime as tflite; print('tflite runtime vesrion:', tflite.__version__);import pycoral; print('pycoral version:', pycoral.__version__)"`

**Comment by bme323** [comment]
Hi thanks,

I reset rpi OS. think initial problem was the pyenv directory but have now run into a new issue about failing to load delegate from libedgetpu. I've created a new issue, and have closed this. Thanks
