### ISSUE TITLE
ValueError: Failed to load delegate from libedgetpu.so.1

### ISSUE THREAD

**Issue by bme323** [google-coral/pycoral#108]
### Description

Hi,

Attempting to follow the Get Started with Coral USB accelerator https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu and getting the error output 'ValueError: Failed to load delegate from libedgetpu.so.1' as shown.

![image](https://user-images.githubusercontent.com/84109305/224502026-747d3c77-8ae4-476f-a8a6-e992a8cc477e.png)

I have attempted to follow issues with the same error but I get error messages when trying to add the apex user using the command 'sudo adduser root apex'.

I am running on Raspberry Pi 4B, arm7l 32-bit, Python 3.9.2

Thank you

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug, Build/Install, Support

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Could you please share the output of below commands:

`python3 -c 'from pycoral.utils.edgetpu import get_runtime_version; print(get_runtime_version())'`

```
sudo python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
```

**Comment by bme323** [comment]
![image](https://user-images.githubusercontent.com/84109305/224852314-9a45b3e1-c59c-40a0-8957-ed41d0104fba.png)

![image](https://user-images.githubusercontent.com/84109305/224852393-3aaca202-a33e-4b0b-86c1-5cb6ed4850e6.png)

**Comment by bme323** [comment]
I get the same initial error message when I run the edge tpu parrot example after running the commands you suggested.

**Comment by CristiFati** [comment]
Make sure the device is connected and visible.
For some reason on my laptop, if I connect it to a certain *USB* port I get this error, but if I move it to another, it works fine.

**Comment by hjonnala** [comment]
Feel free to reopen if issue still exists. Thanks!!
