### ISSUE TITLE
Support for OpenCL backend TFLite runtime package

### ISSUE THREAD

**Issue by rose-jinyang** [google-coral/pycoral#11]
Hello
How are you?
Thanks for contributing to this project.
I am going to install the OpenCL backend Tensorflow Lite runtime package for Python 3.7 on RK3399 device.

OS Platform: Ubuntu 18.04 aarch64
Mobile device: RK3399
GPU: Mali T860
OpenCL: 1.2
gcc(g++): 7.5
CMake: 3.18

Could u provide this asap?
Thanks

**Comment by Namburger** [comment]
@rose-jinyang hello, sorry but OpenCL isn't a supported platform for us. 
I suggest that you drop by the [tensorflow](https://github.com/tensorflow/tensorflow) page for this support
