### ISSUE TITLE
PyCoral library failing to install

### ISSUE THREAD

**Issue by goobags** [google-coral/pycoral#115]
### Description

Hi,

I have been trying to get my Coral TPU M.2 up an running on a Windows machine and struggling. I am a Mac user, so Windows is a bit foreign to me.

Running the following code in Windows Terminal

`python3 -m pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0`

Gives:

```
Looking in indexes: https://pypi.org/simple, https://google-coral.github.io/py-repo/
ERROR: Could not find a version that satisfies the requirement pycoral~=2.0 (from versions: 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
ERROR: No matching distribution found for pycoral~=2.0
```

I know the solution is probably staring me in the face, but I just can't get it. Running on Windows 10, x64 Intel based. I'm not that great with python (3.10 from my understanding) so I am wondering if that is my problem.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Windows 10

### Coral Device

M.2 Accelerator A+E

### Other Devices

Raspberry Pi 3

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
> (3.10 from my understanding) so I am wondering if that is my problem.

yes, we don't have the wheels for python 3.10. If possible, please try with python 3.9. Thanks!!
