### ISSUE TITLE
Linux install issue

### ISSUE THREAD

**Issue by Cganzorig** [google-coral/pycoral#2]
I could not install pycoral on Linux. Seems like the link is broken: 
https://github.com/google-coral/pycoral/releases/download/release-frogfish/pycoral-1.0.0-py3-none-any.whl

**Comment by Namburger** [comment]
@Cganzorig sorry, where did you get the link from?
Here is where you can get the right package for your system:
https://github.com/google-coral/pycoral/releases/

**Comment by Cganzorig** [comment]
Thanks for the quick answer. It was in the official website:
https://coral.ai/software/#coral-python-api
If possible, could you update the link?

**Comment by Namburger** [comment]
@Cganzorig thanks for reporting, we'll definitely get this fixed
