### ISSUE TITLE
Pycoral with GRPC error

### ISSUE THREAD

**Issue by bomerzz** [google-coral/pycoral#30]
While utilizing the GRPC python library on a raspberry pi, once the `import grpc` line of code is run, the load delegate function will fail to connect to the USB Coral accelerator.  Can someone please advise what steps I can take?

Thank you.

python3-pycoral version: 1.0.1

Using load delegate:
![image](https://user-images.githubusercontent.com/6870198/123768463-edeba880-d8fa-11eb-8d4e-ddccd39e432f.png)
Using a detection engine:
![image](https://user-images.githubusercontent.com/6870198/123768494-f5ab4d00-d8fa-11eb-9c39-580c621df380.png)

**Comment by manoj7410** [comment]
@bomerzz I see that you are working with virtual environment. Is the USB Accelerator visible in your environment. 
Can you share the output of 'lsusb' ?

**Comment by bomerzz** [comment]
![image](https://user-images.githubusercontent.com/6870198/124713546-43dfd200-df33-11eb-9cb2-a1434330b12f.png)

Hi @manoj7410  above is the lsusb output

**Comment by manoj7410** [comment]
@bomerzz lsusb output looks okay. Are you able to run the demo given at : https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu ?

**Comment by bomerzz** [comment]
Yes i am able to however if i add `import grpc` to the demos it will not run as well

**Comment by manoj7410** [comment]
Okay.  Can you paste the detailed error here ?
