### ISSUE TITLE
ModuleNotFoundError: No module named 'pycoral.pybind'

### ISSUE THREAD

**Issue by AkkiSony** [google-coral/pycoral#34]
I am new to Coral TPU. I am using this USB accelerator and trying to get the initial demo run and monitor the inference time. 
But, I am getting this error. Please let me know if you have any leads?
Thanks in advance guys! :)

![Coral-TPU](https://user-images.githubusercontent.com/85996229/126780217-5bf5b76e-6373-4fc8-8a34-cb5fba189465.PNG)

**Comment by hjonnala** [comment]
Hi, Let me know your python version. 
please uninstall tflite_runtime and pycoral install it from this whl files: https://github.com/google-coral/pycoral/releases

**Comment by AkkiSony** [comment]
Hi @hjonnala,
My current python version is 3.6.9.

I am just unsure which .whl file, I have to install. As I am using a virtual machine (linux) on host(windows), I am sure that I have to use linux_x86-64. However, I am not sure about cp35, cp36. Can you please elaborate to me what does this indicate? Thank you for responding! :)

**Comment by manoj7410** [comment]
cp35 means that it is compatible with Python3.5 and cp36 means that it is compatible with Python3.6.

**Comment by AkkiSony** [comment]
Thank you for the clarity! :) @manoj7410

![coral-TPU-error1](https://user-images.githubusercontent.com/85996229/126948381-bde2a307-d6d7-49d6-a708-97d70ba5162c.PNG)

I installed pycoral and tflite_runtime as per your suggestion. Since I have python version 3.6, I installed the corresponding cp36.

Now, I am getting the following error when I run the demo as shown on the coral page. Please let me know what am I missing.

**Comment by manoj7410** [comment]
@AkkiSony Are you able to see the USB Accelerator in the output of the command:
- lsusb

**Comment by AkkiSony** [comment]
I cannot find it! :/

However, I can see it on the  settings -> USB. Do you have any suggestions?

![coral-TPU-error2](https://user-images.githubusercontent.com/85996229/126951133-c9a5bb5f-0ef0-4c3f-a2b1-6b5380b81b8d.PNG)

**Comment by AkkiSony** [comment]
![coral-TPU-error3](https://user-images.githubusercontent.com/85996229/126951600-923c2d17-2b76-4be1-b1d0-f327a96a6483.PNG)

That's my output! Is it also called Google Inc ?

**Comment by AkkiSony** [comment]
I could find Gloabal UniChip after unplugging and plugging the USB device again. 
However, I still have the "ValueError: Failed to load delegate from libedgetpu.so.1" error.

Please find the attached screenshot.
![coral-TPU-error4](https://user-images.githubusercontent.com/85996229/126952437-da2be86d-7615-477f-be7e-f648705763bf.PNG)

**Comment by AkkiSony** [comment]
One thing that I noticed is that when I execute the classify_image.py, I can visualize the Global UniChip for few seconds, and after sometime it dissapears! :/ 
After I get this Value error, when I do 
- lsusb
I cannot find the device! :/

Do you have any suggestions?

**Comment by manoj7410** [comment]
So this is how the USB Accelerator works, while connecting the device with your host PC, the Vendor name will appear as : Global Chip Inc. but once you run the first inference, the Vendor name will change to 'Google Inc'. 
VM is not officially supported by Coral because of various challenges related to IO operations and restrictions.

**Comment by AkkiSony** [comment]
Sometimes it works. But it says "Aborted (core dumped)". Can you please let me know why? This is an example code as I said before.
![coral-TPU-error5](https://user-images.githubusercontent.com/85996229/126963425-4a38c569-08e7-403a-aed2-48ae28760478.PNG)

**Comment by AkkiSony** [comment]
Hi,
As VM is not supported, I decided to shift to Windows(host) installation. During the initial steps of installation. 
https://coral.ai/docs/accelerator/get-started/#runtime-on-windows
When I run the .bat file, a command prompt opens and closes every second. This cycle keeps going on. Can you please tell me why am I facing this strange issue?

**Comment by manoj7410** [comment]
@AkkiSony Do you see any error too? I haven't seen this behavior yet.

**Comment by AkkiSony** [comment]
I do not see any error. The cmd prompt opens and closes within one second. And this keep going on until I close the window. It just keeps flashing in and out! :/

**Comment by manoj7410** [comment]
@hjonnala Do you have a Windows machine available with you? If yes, then can you please try to execute the instructions given at: https://coral.ai/docs/accelerator/get-started/#runtime-on-windows ?

**Comment by AkkiSony** [comment]
Hi,
I am following the instructions as per the website. I installed Visual Studio C++ 2019 Redistributable. Later, I also unzipped the file and now when I try to install using the batch file, I get this problem of continous flashing of command prompt. I have no idea about the reason for this! :/

**Comment by AkkiSony** [comment]
Hi, Sorry it was organisational issue. After I clicked on the .bat file, it required me to enter the admin right. After entering the admin rights, things worked fine. Now I am able to install them! :)

**Comment by AkkiSony** [comment]
Just a small question with the istallaton procedure for windows system.
Should this be done in an Anaconda platform? If not, then should we create a virtual enviroment and then install the packages like tensorflow_lite and pycoral?

**Comment by hjonnala** [comment]
It should be fine in an Anaconda platform too. Let us know if you are facing any issues.

**Comment by AkkiSony** [comment]
I am facing this issue when I execute "bash examples/install_requirements.sh classify_image.py"
![coral-TPU-error6](https://user-images.githubusercontent.com/85996229/126996916-98714e8e-d4ba-46b8-8036-83c6314f173e.PNG)

**Comment by hjonnala** [comment]
please install git bash and try to run those commands.

For instructions please refer to: https://coral.ai/docs/dev-board/get-started/#other-windows-requirements

**Comment by AkkiSony** [comment]
Thanks for the answer. That helped me. But since I have to execute these commands on git bash, why do I require Anaconda? 

- How do I create a virtual environment to install the dependencies and libraries?

Please find the output of the command below. Still the test_data directory remain empty! :(

_**$ bash examples/install_requirements.sh examples/classify_image.py
Usage:
  install_requirements.sh [filename]

  Provide the name of an example file in this directory to
  download only the files required for that example.
  If no filename provided, it downloads all example files.
  All files go into the pycoral/test_data/ directory.**_

**Comment by AkkiSony** [comment]
$ bash examples/install_requirements.sh classify_image.py
NOT FOUND: mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite
NOT FOUND: mobilenet_v2_1.0_224_inat_bird_quant.tflite
NOT FOUND: inat_bird_labels.txt
NOT FOUND: parrot.jpg

**Comment by hemanthreddyjonnala** [comment]
I am not sure why the files are not getting downloaded. 

Script trying to download files form this link, can you check if this link working or not on your Machine: 
https://github.com/google-coral/test_data/raw/master/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite

![bash_examples](https://user-images.githubusercontent.com/31050644/127002522-59fddefc-32ee-4aed-ac68-8b2732f293f6.PNG)

**Comment by AkkiSony** [comment]
The link works fine. It downloaded the model as soon as I clicked it!
But why is it not possible through the script? 
Do I have to install pycoral and edgetpu only from.whl files?

**Comment by hemanthreddyjonnala** [comment]
Please install edgetpu runtime from zip file (https://coral.ai/docs/accelerator/get-started#runtime-on-windows)

tflite_runtime and pycoral from .whl files 

can you try these two commands on bash terminal.

curl -Lso /dev/null -w "%{http_code}" "https://github.com/google-coral/test_data/raw/master/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite"

curl -OL "https://github.com/google-coral/test_data/raw/master/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite"

**Comment by AkkiSony** [comment]
The two commands on bash terminal gave me the output as follows.

![coral-TPU-error-7](https://user-images.githubusercontent.com/85996229/127009084-d42feb56-9c18-431a-aeee-22b7271dc0ab.PNG)

**Comment by hjonnala** [comment]
the first should give 200 response. Please check with your organization team why the connection is refused.

**Comment by AkkiSony** [comment]
Please find the below screenshot. When I execute that command, neither am I getting output nor any error. :/
![coral-TPU-error-8](https://user-images.githubusercontent.com/85996229/127016953-b26bf2b2-8e07-4856-903d-505ce557d945.PNG)

**Comment by AkkiSony** [comment]
**tflite_runtime and pycoral from .whl files**

For this, do we have to create a virtual environment and then install? I am sorry, I have not worked much on windows side.

**Comment by hjonnala** [comment]
virtual environment or without virtual environment both would work..

**Comment by hjonnala** [comment]
> Please find the below screenshot. When I execute that command, neither am I getting output nor any error. :/
> ![coral-TPU-error-8](https://user-images.githubusercontent.com/85996229/127016953-b26bf2b2-8e07-4856-903d-505ce557d945.PNG)

can you try these two commands:

python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg

py examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg

**Comment by AkkiSony** [comment]
@hjonnala Can you please give me a short description, how do you install using whl files on windows side?

> virtual environment or without virtual environment both would work.

**Comment by AkkiSony** [comment]
@hjonnala Thank you for your reply!

> virtual environment or without virtual environment both would work..

Can you please give me a short description how to install .whl files on windows side. I am confused because, on Anaconda platform we can create virtual environment and then instal using pip command. But on Git bash, since there is no pip installed, how do we do it? Can you please guide me with a short description?

**Comment by hemanthreddyjonnala** [comment]
For pip installations  You can use anaconda platform as you described above. 

On bash run pip install command with python executable.
sample command: c:\\pyhton36\\python.exe -m pip install numpy

**Comment by AkkiSony** [comment]
Thank you for your input. It really helped to. I added the path of Python and Pip to my PATH variable.

But  when I try to install the .whl files, I am getting these error.
![coral-TPU-error-9](https://user-images.githubusercontent.com/85996229/127189191-0f442742-d5c6-47be-864f-fc420367f77c.PNG)

**Comment by hjonnala** [comment]
You are trying install linux versions.

we have new releases. 
Please install 

edgetpu runtime form this (https://github.com/google-coral/libedgetpu/releases/download/release-grouper/edgetpu_runtime_20210726.zip)
and tflite runtime and pycoral from below:
if your python version is 3.6 for windows:
```
pip3 install https://github.com/google-coral/pycoral/releases/download/v2.0.0/tflite_runtime-2.5.0.post1-cp36-cp36m-win_amd64.whl
pip3 install https://github.com/google-coral/pycoral/releases/download/v2.0.0/pycoral-2.0.0-cp36-cp36m-win_amd64.whl

```

**Comment by AkkiSony** [comment]
Thank you for making me notice that I was installing the linux version. I am sorry for that! :)

Whe I try to run the example, I am getting the below error. Please can you guide me for the same? :) I thank you in advance for your time! 
![coral-TPU-error-10](https://user-images.githubusercontent.com/85996229/127482274-a06451eb-c939-4c46-a5a1-dc55cf1b8907.PNG)

**Comment by hjonnala** [comment]
Hi, which python version version you are using?

I think it's due to pillow version. can you try this

pip uninstall pillow
pip install Pillow==8.3.1

**Comment by AkkiSony** [comment]
Hello @hjonnala ,
$ python --version
Python 3.8.8

I uninstalled Pillow version 8.2. 
While installing Pillow==8.3.1, I am getting an error

![coral-TPU-error-11](https://user-images.githubusercontent.com/85996229/127489561-fb644d0c-cd6a-4d80-ad49-6eff0a3faed0.PNG)

**Comment by hjonnala** [comment]
can you create new virtual environment and try this command.

python3 -m pip install --index-url https://google-coral.github.io/py-repo/ --extra-index-url=https://pypi.python.org/simple pycoral

if python3 not working try:
py -m pip install --index-url https://google-coral.github.io/py-repo/ --extra-index-url=https://pypi.python.org/simple pycoral

**Comment by AkkiSony** [comment]
I activated the default virtual environment "base". 
After executing the above command, I am getting the same error as above.

I even tried to add them to trusted hosts.
python -m pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org --upgrade pip 

Yet the same error as the image attached in the previous thread! :(

**Comment by hjonnala** [comment]
Instead of base can you please create new virtual environment and paste the entire output of 
python3 -m pip install --index-url https://google-coral.github.io/py-repo/ --extra-index-url=https://pypi.python.org/simple pycoral

**Comment by AkkiSony** [comment]
> can you create new virtual environment and try this command.
> 
> python3 -m pip install --index-url https://google-coral.github.io/py-repo/ --extra-index-url=https://pypi.python.org/simple pycoral
> 
> if python3 not working try:
> py -m pip install --index-url https://google-coral.github.io/py-repo/ --extra-index-url=https://pypi.python.org/simple pycoral

I tried these commands after creating a new virtual environment using conda platform, yet I have these errors. 

I even added proxy by using 
set http_proxy=.....
set https_proxy=....

![coral-TPU-error-12](https://user-images.githubusercontent.com/85996229/127717085-64a381ff-df9a-46c9-a73d-d1eb5d833992.PNG)

**Comment by AkkiSony** [comment]
I solved the above error by adding an extra command. Hope it helps someone with the same error. :)

 pip install pycoral-1.0.1-cp38-cp38-win_amd64.whl -i http://pypi.douban.com/simple- -trusted-host pypi.douban.com

**Comment by AkkiSony** [comment]
> the first should give 200 response. Please check with your organization team why the connection is refused.

I now getting segmentation fault as the output for both the statements. Can you help me solve the issue please?
![coral-TPU-error-13](https://user-images.githubusercontent.com/85996229/127833740-0d9c892a-89a9-4b00-ade5-09db5278cf97.PNG)
