### ISSUE TITLE
Get Started Directions for USB Accelerator on RPi4 - No module named pycoral.adapters

### ISSUE THREAD

**Issue by RogerWebb** [google-coral/pycoral#45]
### Description

Refererence:  https://coral.ai/docs/accelerator/get-started

Following the instructions at the above reference URL, I was able to build and install the Edge TPU Runtime (libedgetpu1-std) and PyCoral via the specified "sudo apt-get install python3-pycoral" and I see it's at the current version (a re-run of the command gets a "python3-pycoral is already at the newest version (2.0.0)".  I have run the install_requirements.sh script which completed successfully.  Running any of the example scripts (ie. examples/detect_image.py) gives an ImportError.  Please advise.

### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.7

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "examples/classify_image.py", Line 37, in <module>
    from pycoral.adapters import classify
ImportError: No module named pycoral.adapters
```

**Comment by scottamain** [comment]
Hi @RogerWebb, did you resolve this? If so, please let us know what the problem was in case others encounter this as well.
