### ISSUE TITLE
How to run yolov5(pytroch) in google-TPU Dev Board

### ISSUE THREAD

**Issue by luckywangchenxi** [google-coral/pycoral#54]
### Description

Hi, I am a student and I want to deploy yolov5 to google-TPU Dev Board.
I would like to ask how to run https://github.com/ultralytics/yolov5 on google-TPU Dev Board (https://coral.ai/products/dev-board) .
From what I have checked so far
1. Need to convert pytorch to TensorFlow via onnx.
2.  Convert tflite model to tflite-tpu model.
3. Then deploy to google-TPU development board.
If you can describe the exact process, it would be greatly appreciated, thanks!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Feel free to reopen if you have questions.

**Comment by atbdeveloper** [comment]
Anyone knows about the process for run Yolo V9 inside google coral board?

**Comment by CarlosNacher** [comment]
> ### Description
> Hi, I am a student and I want to deploy yolov5 to google-TPU Dev Board. I would like to ask how to run https://github.com/ultralytics/yolov5 on google-TPU Dev Board (https://coral.ai/products/dev-board) . From what I have checked so far
> 
> 1. Need to convert pytorch to TensorFlow via onnx.
> 2. Convert tflite model to tflite-tpu model.
> 3. Then deploy to google-TPU development board.
>    If you can describe the exact process, it would be greatly appreciated, thanks!
> 
> Click to expand!

Hey @luckywangchenxi ! I am trying to convrt pytorch to tensorflow but it is proving frustrating, could you please help me?

I have converted from pytorch to onnx, which is simple with `torch.onnx.export()` method. But the step to convert onnx to tensorflow, I don't find any library that achieves it. I found https://github.com/onnx/onnx-tensorflow but it has not been mantained for 2 years and when I try it, a lot of dependency errors raise. I would really appreciate your help, thank you in advance!

**Comment by luckywangchenxi** [comment]
> > ### Description
> > Hi, I am a student and I want to deploy yolov5 to google-TPU Dev Board. I would like to ask how to run https://github.com/ultralytics/yolov5 on google-TPU Dev Board (https://coral.ai/products/dev-board) . From what I have checked so far
> > 
> > 1. Need to convert pytorch to TensorFlow via onnx.
> > 2. Convert tflite model to tflite-tpu model.
> > 3. Then deploy to google-TPU development board.
> >    If you can describe the exact process, it would be greatly appreciated, thanks!
> > 
> > Click to expand!
> 
> Hey @luckywangchenxi ! I am trying to convrt pytorch to tensorflow but it is proving frustrating, could you please help me?
> 
> I have converted from pytorch to onnx, which is simple with `torch.onnx.export()` method. But the step to convert onnx to tensorflow, I don't find any library that achieves it. I found https://github.com/onnx/onnx-tensorflow but it has not been mantained for 2 years and when I try it, a lot of dependency errors raise. I would really appreciate your help, thank you in advance!

Sorry, I am no longer working on this project. I wish you all the best.

**Comment by luckywangchenxi** [comment]
> > ### Description
> > Hi, I am a student and I want to deploy yolov5 to google-TPU Dev Board. I would like to ask how to run https://github.com/ultralytics/yolov5 on google-TPU Dev Board (https://coral.ai/products/dev-board) . From what I have checked so far
> > 
> > 1. Need to convert pytorch to TensorFlow via onnx.
> > 2. Convert tflite model to tflite-tpu model.
> > 3. Then deploy to google-TPU development board.
> >    If you can describe the exact process, it would be greatly appreciated, thanks!
> > 
> > Click to expand!
> 
> Hey @luckywangchenxi ! I am trying to convrt pytorch to tensorflow but it is proving frustrating, could you please help me?
> 
> I have converted from pytorch to onnx, which is simple with `torch.onnx.export()` method. But the step to convert onnx to tensorflow, I don't find any library that achieves it. I found https://github.com/onnx/onnx-tensorflow but it has not been mantained for 2 years and when I try it, a lot of dependency errors raise. I would really appreciate your help, thank you in advance!

Sorry, I am no longer working on this project. I wish you all the best.

**Comment by CarlosNacher** [comment]
@luckywangchenxi don't worry, thank you for your quick response. As help for others with the same problem, **I have been able to convert onnx to tensorflow with the following repo**: https://github.com/PINTO0309/onnx2tf
