### ISSUE TITLE
edgetpu.make_interpreter fails without printing error (WIN, PY3.8)

### ISSUE THREAD

**Issue by norton-chris** [google-coral/pycoral#57]
### Description

Hi,
Been having a lot of trouble building and getting pycoral to work. Running on Windows, anaconda prompt, and python 3.8 is the only setup I've been able to get to run without any build or import errors.
I am running into a problem with edgetpu.make_interpreter specifically. When I run my program it gets to `interpreter = edgetpu.make_interpreter("model.tflite")` and then the program just ends. I have print statements on both sides of it and the one after doesn't show up. 

Any ideas on how to fix this?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Programming Language

Python 3.8

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Is it the same model (mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite) you are not getting print statements after make_interpreter call or a different model. If its different model, can you please share the model.

Also, are you working with custom build libraries or pre build ones?

**Comment by norton-chris** [comment]
Using a custom model, but just tried that model and I get the same results.

Here's the code snippet I'm running:
print("make interpreter", args.model)
interpreter = edgetpu.make_interpreter("pycoral/test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite")
#interpreter = make_interpreter("model.tflite@:0")
print("allocate_tensors")
interpreter.allocate_tensors()

It would hit make interpreter and stall and then quit after a 10 seconds or so.
I'm actually seeing this error that was previously in a try except so I took that out and got this error.
ImportError: generic_type: type "InterpreterWrapper" is already registered!

However another thing that is weird, if I run the semantic_segmentation.py file in the examples. It runs and give that same output (if verbosity is set, else it does nothing) and then just quits.

Here's that output:

(tf-3.8) C:\Users\chris\OneDrive\Documents\RSE\pycoral>python examples/semantic_segmentation.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --input test_data/bird.bmp --keep_aspect_ratio --output segmentation_result.jpg
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:998] EnumerateDevices: found [/sys/bus/usb/devices/1-14]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/beagle/beagle_usb_driver_provider.cc:218] Enumerate: adding path [/sys/bus/usb/devices/1-14]
I driver/driver_factory_windows.cc:29] DriverFactoryWin::EnumerateByClass()...
I driver/driver_factory_windows.cc:75] DriverFactoryWin::EnumerateByClass returns empty list.
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:998] EnumerateDevices: found [/sys/bus/usb/devices/1-14]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/beagle/beagle_usb_driver_provider.cc:218] Enumerate: adding path [/sys/bus/usb/devices/1-14]
I driver/driver_factory_windows.cc:29] DriverFactoryWin::EnumerateByClass()...
I driver/driver_factory_windows.cc:75] DriverFactoryWin::EnumerateByClass returns empty list.
I tflite/edgetpu_context_direct.cc:106] USB always DFU: False (default)
I tflite/edgetpu_context_direct.cc:147] USB bulk-in queue capacity: 8
I tflite/edgetpu_context_direct.cc:63] Performance expectation: High when USB connected EdgeTpu is throttled
I driver/usb/usb_driver.cc:1383] Open device and check if DFU is needed
I driver/usb/local_usb_device.cc:1013] OpenDevice: [/sys/bus/usb/devices/1-14]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[5]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[7]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:1081] OpenDevice: device opened 000001B47CC9D250
I driver/usb/local_usb_device.cc:184] LocalUsbDevice
I driver/usb/usb_standard_commands.cc:36] UsbStandardCommands
I driver/usb/usb_dfu_commands.cc:37] UsbDfuCommands
I driver/usb/usb_standard_commands.cc:43] GetDeviceDescriptor
I driver/usb/local_usb_device.cc:398] GetDescriptor
I driver/usb/usb_standard_commands.cc:78] Vender ID: 0x1a6e
I driver/usb/usb_standard_commands.cc:79] Product ID: 0x89a
I driver/usb/usb_driver.cc:1417] Device is in DFU mode
I driver/usb/usb_driver.cc:1422] Resetting device
I driver/usb/local_usb_device.cc:243] Close: closing device 000001B47CC9D250
I driver/usb/local_usb_device.cc:216] DoCancelAllTransfers: cancelling 0 async transfers
I driver/usb/local_usb_device.cc:224] DoCancelAllTransfers: waiting for all async transfers to complete
I driver/usb/local_usb_device.cc:234] DoCancelAllTransfers: all async transfers have completed
I driver/usb/local_usb_device.cc:276] Close: releasing 0 transfer buffers
I driver/usb/local_usb_device.cc:289] Close: performing graceful reset

(tf-3.8) C:\Users\chris\OneDrive\Documents\RSE\pycoral>

**Comment by keesschollaart81** [comment]
I have the same issue? The same code + USB Device that used to work now does not work anymore, since I ran it last, some time ago. I might overlook a change here but the only significant difference I have is my upgrade to Windows 11...?

```
BuildLabel(COMPILER=MSVC 192628805,DATE=Nov  4 2020,TIME=11:05:43), RuntimeVersion(13)
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[10]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[11]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[3] port[1]
I driver/usb/local_usb_device.cc:998] EnumerateDevices: found [/sys/bus/usb/devices/3-1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[5] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[9] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[6]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[8]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[10]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[11]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[3] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[5] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[9] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[6]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[8]
I driver/beagle/beagle_usb_driver_provider.cc:218] Enumerate: adding path [/sys/bus/usb/devices/3-1]
I driver/driver_factory_windows.cc:29] DriverFactoryWin::EnumerateByClass()...
I driver/driver_factory_windows.cc:75] DriverFactoryWin::EnumerateByClass returns empty list.
Device 0: EDGETPU_APEX_USB, /sys/bus/usb/devices/3-1
I tflite/edgetpu_manager_direct.cc:453] No matching device is already opened for shared ownership.
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x1a6e, product:0x89a
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[10]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[11]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[3] port[1]
I driver/usb/local_usb_device.cc:998] EnumerateDevices: found [/sys/bus/usb/devices/3-1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[5] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[9] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[6]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[8]
I driver/usb/local_usb_device.cc:944] EnumerateDevices: vendor:0x18d1, product:0x9302
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[10]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[1] port[11]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[2] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[3] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[5] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[1]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[8] port[2]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[9] port[3]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[4]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[5]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[6]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[7]
I driver/usb/local_usb_device.cc:979] EnumerateDevices: checking bus[10] port[8]
I driver/beagle/beagle_usb_driver_provider.cc:218] Enumerate: adding path [/sys/bus/usb/devices/3-1]
I driver/driver_factory_windows.cc:29] DriverFactoryWin::EnumerateByClass()...
I driver/driver_factory_windows.cc:75] DriverFactoryWin::EnumerateByClass returns empty list.
I tflite/edgetpu_context_direct.cc:107] USB always DFU: True
I tflite/edgetpu_context_direct.cc:145] USB bulk-in queue capacity: 8
I tflite/edgetpu_context_direct.cc:65] Performance expectation: Max (default)
I driver/usb/usb_driver.cc:1386] Open device and check if DFU is needed
I driver/usb/local_usb_device.cc:1013] OpenDevice: [/sys/bus/usb/devices/3-1]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[3]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[10]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[4]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[11]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[2] port[3]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[3] port[1]
I driver/usb/local_usb_device.cc:60] ConvertLibUsbError: USB error -99 [OpenDevice]
I driver/usb/local_usb_device.cc:1013] OpenDevice: [/sys/bus/usb/devices/3-1]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[3]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[10]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[4]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[14]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[1] port[11]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[2] port[3]
I driver/usb/local_usb_device.cc:1050] OpenDevice: checking bus[3] port[1]
```

And then repeating this loop...

I'm not running Python, I C#bindings to edgetpu.dll similar to [these](https://github.com/harujoh/TensorFlowLiteNet/blob/c550115b8dcec75e4db6d83efff77a5dd48ec08c/TensorFlowLiteNet/NativeMethods.cs#L51). I'm running my app as administrator and tried multiple USB ports. Upgrading/Downgrading from/to Grouper did not make any difference (other than the output of `edgetpu_version`. I did reboot my machine in between upgrade/downgrades.

Is this the same issue or do you want me to create a new issue?

**Comment by hjonnala** [comment]
Hi @keesschollaart81 we haven't tested the USB accelerator and software with windows 11 yet. If possible, can you please test with windows 10?

**Comment by keesschollaart81** [comment]
Yeah, will test on the laptop of my colleague tomorrow morning (CEST), will report back here!

**Comment by keesschollaart81** [comment]
Can confirm: same code/device/model-file/driver-version does work on Windows 10 machine. So at least for me, it seems to be an issue with either my machine or Windows 11.

**Comment by norton-chris** [comment]
Sorry school kinda took over my life the last few weeks. Yes, I was having this problem with Windows 11. @keesschollaart81 thanks for testing that out, will try a windows 10 machine.

**Comment by hjonnala** [comment]
@norton-chris @keesschollaart81 I have tested Coral USB accelerator with windows 11 and it is **working.** Please make sure you are running runtime version 13: https://github.com/google-coral/libedgetpu/releases/download/release-frogfish/edgetpu_runtime_20210119.zip

**Comment by hjonnala** [comment]
Feel free to reopen if you are still having the issue. Thanks!
