### ISSUE TITLE
Pretrained models license

### ISSUE THREAD

**Issue by StephenKThung** [google-coral/pycoral#64]
### Description

Hi all, my group is interested in working with some of the [pre-trained models from the coral model zoo](https://coral.ai/models/object-detection/)

We saw that they are marked as "for demonstration purposes only" but have been unable to find a more specific license. Do they simply inherit the licenses from COCO and this repo or are there additional considerations?

Thanks!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @StephenKThung  most of our models and pycoral repo are Apache licensed.

https://github.com/google-coral/pycoral/blob/master/LICENSE
https://github.com/google-coral/test_data/blob/master/LICENSE

**Comment by StephenKThung** [comment]
Thanks for the information!
