### ISSUE TITLE
Debian 10.11, aarch64, and No module named 'pycoral.pybind'

### ISSUE THREAD

**Issue by tom-gall** [google-coral/pycoral#71]
### Description

Hi All,

I seem to have tripped across an issue reported before however the past solution doesn't seem to work.

I've the USB Coral
aarch64 install of Debian 10.11
pycoral-examples$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux

pip3 install --force-reinstall  ~/pycoral-2.0.0-cp37-cp37m-linux_aarch64.whl ~/tflite_runtime-2.5.0.post1-cp37-cp37m-linux_aarch64.whl

where the wheels were downloaded from : https://github.com/google-coral/pycoral/releases

and then this happens:
pycoral-examples$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 40, in <module>
    from pycoral.utils.edgetpu import make_interpreter
  File "/home/tgall/coral/pycoral-examples/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ModuleNotFoundError: No module named 'pycoral.pybind'

Suggestions?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @tom-gall  please try renaming `/home/tgall/coral/pycoral-examples/pycoral/` folder to` /home/tgall/coral/pycoral-examples/pycoral2` or something else and try the demo.

**Comment by tom-gall** [comment]
Bingo! That was it.
