### ISSUE TITLE
Normalize input in object detector example

### ISSUE THREAD

**Issue by Corallo** [google-coral/pycoral#93]
### Description

Hello, I took a look at your object detector example [here](https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py)
That uses SSD mobilenetv2 ([among the suggested parameters](https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py#L26)) from the [coral page](https://coral.ai/models/object-detection/).

Looking with Netron at the network, I see that the input of the network is called: normalized_input_image_tensor.
Does that mean that the network expect the input to be quantized somehow?
If yes, is the normalization missing in the example?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Operating System

Linux

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @Corallo I think normalization and quantization not required for the detection demo. Feel free to add the code from [classify_image.py](https://github.com/google-coral/pycoral/blob/master/examples/classify_image.py#L81) if you wish to do so. Thanks!
