### ISSUE TITLE
common input size expects 4 values

### ISSUE THREAD

**Issue by marinakrcek** [google-coral/pycoral#95]
### Description

from pycoral.adapters import common
size = common.input_size(interpreter)

implementation expects 4 values for the shape, while MLP can can have shape with just, for example, 1 x height x width of the picture.
This is the implementation that throws the error then: _, height, width, _ = input_details(interpreter, 'shape')
ValueError: not enough values to unpack (expected 4, got 3)

Why is that the case?

I use the latest version: 
>>> pycoral.__version__
'2.0.0'

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Operating System

Windows 10, Debian (RPi 4)

### Coral Device

USB Accelerator

### Programming Language

Python

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Seems `input_details(interpreter, 'shape')` is returning only 3 values and your code expecting 4 values.

Please try `_, height, width = input_details(interpreter, 'shape')`
